### PR TITLE
Singleton lazy creation

### PR DESCRIPTION
**Pull request by ChicK00o**

### CODE REVIEW

**Comment by Jblew** [comment]
That's an awesome feature 👍

**Comment by miladrahimi** [comment]
It move the errors from init time to runtime, I'm not ok with this feature.

**Comment by amirrezaask** [comment]
@miladrahimi I don't see how this would significantly improve the performance, since singletons are only created once, also the point you are saying is true, since basically application in any time can crash since it wants to create an object that cannot be created, with current code these errors can only happen in the initialization part of app. This is also why we should tell users to prefer singletons, since they are more robust than other types

**Comment by ChicK00o** [comment]
@miladrahimi @amirrezaask this is not for performance. By making it lazy initialised, it allowed for the idea to register singletons in "init()" function, and not worry about the order, yes this hides the order of creation for the user, but writing a test to check creation, ensure, if there are any issues. 
I have not checked in a large project, but on the smaller personal project this idea helped me, by keeping the registration in init function, my tests became smaller, as i only had to create the object i was testing, and the rest of the object were created. 
Again, now that there is new idea of multi-container, i plan on using it to create ideas of test container that would help in creating dependency with test configuration. i just have not yet come to it, will do those changes later, when i come around to do it

**Comment by GangBoss** [comment]
propably function build()
that will try to create each singleton instance can carry over runtime errors to program initialization time

**Comment by miladrahimi** [comment]
@ChicK00o please update it to v3 to merge it and have this nice feature in next releases.

**Pull request closed without merging**
