### PR TITLE
Lazy singleton construction

### PR DESCRIPTION
**Pull request by Place1**
This PR makes singleton construction lazy. It also adds a lock to each container binding so that multiple goroutines can safely work with the container at the same time.

 This feature is very helpful if you have multiple programs/entrypoints that share the same container but only use a subset of the dependencies.

In my use-case I have a server and cli application that share the same container; there are many shared dependencies but not everything is used by both programs. For example the TLS configuration used by the server isn't used by the cli application and attempting to resolve it will fail because the certificates won't be available.

With this PR the problem is solved because only the dependencies (bindings) that are requested are constructed; if the cli app never requests the TLS configuration then it's resolver is never executed.

### CODE REVIEW

**Comment by Place1** [comment]
I'm happy to write tests if this is something you'd like to merge.

**Comment by Cililing** [comment]
Imho it's a good thing, but it should be an option, not the default choice.

**Comment by miladrahimi** [comment]
I agree with @Cililing

**Comment by miladrahimi** [comment]
How about new methods like `lazySingleton` and `lazyNamedSingleton`?

**Comment by Place1** [comment]
Yeah that sounds reasonable

- `LazySingleton`
- `LazyNamedSingleton`
- `MustLazySingleton`
- `MustLazyNamedSingleton`

**Comment by wirecat** [comment]
@Place1 any updates? This is a feature I'd like to use myself.

**Pull request closed without merging**
