### PR TITLE
Error returning except panic

### PR DESCRIPTION
**Pull request by sedhossein**
In case of any error on this package, we decide to use the built-in `panic()` function that stops the normal execution of the current goroutine. Based on [golang builtin.go](https://github.com/golang/go/blob/master/src/builtin/builtin.go#L232) we have:

> ... This continues until all functions in the executing goroutine have stopped, in reverse order. At that point, the program is terminated with a non-zero exit code. This termination sequence is called panicking and can be controlled by the built-in function recover.

As an injected part of any project, it's not a good deal to call `panic()` and terminate the program with a non-zero exit code. Also, there is no place to explain this important notice to users that they can make any recovery plan for error situations!
I believe Panics are not exceptions and I think it's better to returning an error on error cases and removing `panic()` in all of the repo. And panic is useful for sometimes the program simply cannot continue. The library has not this ownership. The [regexp.MustCompile()](https://github.com/golang/go/blob/master/src/regexp/regexp.go#L308) maybe can a good example of something that may panic.
On the other hand, Golang built-in libs used `panic` in internal packages but it recovers panic in itself too! Take a look on [json.marshal()](https://github.com/golang/go/blob/master/src/encoding/json/encode.go#L320). 

And I think this link prepared a good article for using panics in projects. [Advanced Go Panic Programming](https://hackernoon.com/panic-like-a-pro-89044d5a2d35)

Maybe it's not bad to remember that error handling is one of the in-progress improvements on Golang 
 [Go 2 Draft Designs](https://go.googlesource.com/proposal/+/master/design/go2draft.md)

### CODE REVIEW

**Comment by miladrahimi** [comment]
That's great! But the test coverage is -9.4% decreased, could you please check it.

**Comment by sedhossein** [comment]
> That's great! But the test coverage is -9.4% decreased, could you please check it.

I see, The uncovered lines never run with this logic! They just happen when we have some wrong changes in it. And uncovered lines just run when we have below the failure chain:

1. `Make(abstraction)` call
2. Check `concrete = container[abstraction]` exists or not? If its not exist we  cover this situations
3. If it exists, program call `concrete.resolve()`
4. `resolve()` may have an error on calling `invoke(resolver)`
5. On `invoke(resolver), `arguments(function)` calls.
6. `arguments(function interface{})` check `container[abstraction]` again! and if it can be not exist, we can run uncovered lines! It's impossible. because we check this before on `Make()`

Now to cover this line with any way that possible, We can making something like this:
```go
type Handler interface {
	invoke(function interface{}) (interface{}, error)
	bind(resolver interface{}, singleton bool)
	arguments(function interface{}) ([]reflect.Value, error)
}

var handler Handler

func Init(h Handler) {
   handler = h
}
```
to can mock internal handler functions! or expose them to use monkey-patch hack for them.

I believe this coverage decrease is not harmful actually. But if you have any better idea I can work on it.

**Comment by miladrahimi** [comment]
The GoAwesome doesn't accept 95% and lower coverage :(

**Comment by sedhossein** [comment]
@miladrahimi Jan, After a while, I can work on my PR again.
I updated it with the new structure and in the new style, there is no issue with test coverages.

**Pull request merged**
